FROM python:3.10-slim

WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir -e .
COPY src/ ./src/
COPY data/raw/movies.csv ./data/raw/movies.csv
COPY data/processed/popularity.csv ./data/processed/popularity.csv

EXPOSE 8000
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
